apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb-port-27017
    protocol: TCP
  - port: 27018
    targetPort: 27018
    name: mongodb-port-27018
    protocol: TCP
  - port: 27019
    targetPort: 27019
    name: mongodb-port-27019
    protocol: TCP
  type: ClusterIP
