apiVersion: v1
kind: Service
metadata:
  name: planner
  labels:
    app: planner
spec:
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: planner-port
  selector:
    app: planner
  type: ClusterIP