apiVersion: v1
kind: Service
metadata:
  name: serverservice
  labels:
    app: serverservice
spec:
  selector:
    app: serverservice
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: serverservice-port
  type: ClusterIP
