# TOPO
---
apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  name: toposervice
  labels:
    app: toposervice
spec:
  selector:
    app: toposervice
  ports:
  - port: 8181
    targetPort: 8181
    protocol: TCP
    name: toposervice-port
  type: ClusterIP