apiVersion: v1
kind: Service
metadata:
  name: weatherservice
  labels:
    app: weatherservice
spec:
  selector:
    app: weatherservice
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP