kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv
spec:
  storageClassName: mongodb-class
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db/mongo"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-pvc
spec:
  storageClassName: mongodb-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

