apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: {{ .Values.mongodb.image.name }}:{{ .Values.mongodb.image.version }}        
        ports:
        - containerPort: 27017
          name: mongodb-27017
        - containerPort: 27018
          name: mongodb-27018
        - containerPort: 27019
          name: mongodb-27019
        env:
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_HOST
          value: mongodb
        - name: MONGO_INITDB_DATABASE
          value: topoDB
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: password
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc
