apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image.name }}:{{ .Values.rabbitmq.image.version }}        
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_DEFAULT_USER
          value: root
        - name: RABBITMQ_DEFAULT_PASS
          value: password
  replicas: 1
