# SERVER
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      restartPolicy: Always
      containers:
      - name: server
        image: mastercloudapps/server:v1.23
        ports:
        - containerPort: 8080
        env:
        - name: QUARKUS_DATASOURCE_DB_KIND
          value: mysql
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: jdbc:mysql://mysql/eoloplantsDB
        - name: QUARKUS_DATASOURCE_USERNAME
          value: root
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: password
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USERNAME
          value: root
        - name: RABBITMQ_PASSWORD
          value: password
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
  - port: 8080
    targetPort: 8080
    name: server-port
  type: ClusterIP
